apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec: 
  replicas: 2
  selector: 
    matchLabels:
      split: blue
  template:
    metadata:
      labels:
        splits: blue
        app: colores
    spec: 
      containers:
      - name: app
        image: linuxacademycontent/summit-k8s:blue
        ports:
        - containerPort: 80
        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec: 
  replicas: 2
  selector: 
    matchLabels:
      split: green
  template:
    metadata:
      labels:
        splits: green
        app: colores
    spec: 
      containers:
      - name: app
        image: linuxacademycontent/summit-k8s:green
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: servicio
spec:
  type: NodePort
  selector: 
    app: colores
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081