apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: deployment
  template: 
    metadata:
      labels:
        app: deployment
    spec:
      containers: 
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80